import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003064",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-surface-variant": "#b9cacb",
        "on-tertiary-fixed-variant": "#673d00",
        "outline-variant": "#3b494b",
        "surface-container": "#1b2029",
        "background": "#0e141c",
        "outline": "#849495",
        "primary-container": "#00f0ff",
        "surface": "#0e141c",
        "on-primary-fixed-variant": "#004f54",
        "on-tertiary": "#482900",
        "tertiary-fixed-dim": "#ffb869",
        "surface-bright": "#343943",
        "on-secondary-fixed-variant": "#00468d",
        "primary-fixed": "#7df4ff",
        "secondary-container": "#3e90ff",
        "inverse-surface": "#dee2ef",
        "on-surface": "#dee2ef",
        "on-tertiary-fixed": "#2c1700",
        "surface-tint": "#00dbe9",
        "inverse-primary": "#006970",
        "surface-container-low": "#171c25",
        "secondary-fixed-dim": "#aac7ff",
        "tertiary-container": "#ffd1a3",
        "surface-container-lowest": "#090e17",
        "primary": "#dbfcff",
        "tertiary-fixed": "#ffdcbb",
        "surface-dim": "#0e141c",
        "on-secondary-fixed": "#001b3e",
        "surface-variant": "#30353e",
        "surface-container-highest": "#30353e",
        "on-background": "#dee2ef",
        "surface-container-high": "#252a33",
        "on-secondary-container": "#002957",
        "on-tertiary-container": "#895200",
        "secondary": "#aac7ff",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "tertiary": "#fff4ec",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d6e3ff",
        "inverse-on-surface": "#2b313a",
        "on-primary-container": "#006970",
        "on-primary": "#00363a",
        // Holo specific colors from the design
        "holo-cyan": "#00f0ff",
        "holo-cyan-glow": "#38bdf8",
        "holo-deep": "#020409",
        "holo-surface": "rgba(4, 10, 22, 0.78)",
        "holo-border": "rgba(0, 240, 255, 0.22)",
        "holo-amber": "#f59e0b",
        "holo-amber-glow": "#fbbf24",
        "holo-orange": "#ff5500",
        "holo-red": "#ff4d4d",
        "holo-text": "#f8fafc",
        "holo-muted": "#64748b",
      },
      fontFamily: {
        "telemetry-lg": ["var(--font-jetbrains-mono)", "monospace"],
        "telemetry-md": ["var(--font-jetbrains-mono)", "monospace"],
        "telemetry-sm": ["var(--font-jetbrains-mono)", "monospace"],
        "telemetry-micro": ["var(--font-jetbrains-mono)", "monospace"],
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-md": ["var(--font-plus-jakarta)", "sans-serif"],
        "headline-sm": ["var(--font-plus-jakarta)", "sans-serif"],
        "display-hero": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "telemetry-micro": ["9px", { lineHeight: "12px", letterSpacing: "0.14em", fontWeight: "600" }],
        "telemetry-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.10em", fontWeight: "500" }],
        "telemetry-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "400" }],
        "telemetry-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-md": ["13px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "body-lg": ["15px", { lineHeight: "24px", letterSpacing: "0.015em", fontWeight: "300" }],
        "headline-sm": ["16px", { lineHeight: "22px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "0.04em", fontWeight: "500" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "0.06em", fontWeight: "400" }],
        "display-hero": ["48px", { lineHeight: "56px", letterSpacing: "0.08em", fontWeight: "300" }],
      },
    },
  },
  plugins: [],
};

export default config;
